/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import bbdd.conexion;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modelo.Administracion;
import modelo.Fichero;

/**
 *
 * @author Brayan
 */
public class CandidatosAdministracion extends javax.swing.JDialog {

    /**
     * Creates new form nuevoalumnoo
     */
    
    File fca;
    FileWriter fr;
    PrintWriter pr;
            
    public CandidatosAdministracion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cficfhero();
    }
    
    public void cficfhero() {
        fca = new File("CandidatosAdministracion.txt");

        if (!fca.exists()) {
            try {
                fca.createNewFile();
                fr = new FileWriter(fca);
                pr = new PrintWriter(fr);
                pr.write("----------CANDIDATOS ADMINISTRACION---------");
            } catch (IOException ex) {
                Logger.getLogger(CandidatosAdministracion.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    fr.close();
                    pr.close();
                } catch (IOException ex) {
                    Logger.getLogger(CandidatosAdministracion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_dni = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_cp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_localidad = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        btn_cargarcv = new javax.swing.JButton();
        Date_calendario = new com.toedter.calendar.JDateChooser();
        btn_registrar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_observaciones = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btn_estudiosfinalizados = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_usuariotextos = new javax.swing.JRadioButton();
        btn_usuariocalculos = new javax.swing.JRadioButton();
        btn_avanzadotextos = new javax.swing.JRadioButton();
        btn_mediocalculo = new javax.swing.JRadioButton();
        btn_avanzadocalculo = new javax.swing.JRadioButton();
        btn_usuariointernet = new javax.swing.JRadioButton();
        btn_mediotextos = new javax.swing.JRadioButton();
        btn_mediointernet = new javax.swing.JRadioButton();
        btn_avanzadointernet = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 700));
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setPreferredSize(new java.awt.Dimension(1100, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ALTA NUEVO CANDIDATO ADMINISTRACIÓN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Nombre");

        txt_nombre.setBackground(new java.awt.Color(255, 255, 255));
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Apellidos");

        txt_apellidos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Dni");

        txt_dni.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Fecha de nacimiento");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Direccion");

        txt_direccion.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("CP");

        txt_cp.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Localidad");

        btn_localidad.setBackground(new java.awt.Color(204, 204, 204));
        btn_localidad.setForeground(new java.awt.Color(0, 0, 0));
        btn_localidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Zaragoza", "Hueca", "Teruel" }));
        btn_localidad.setToolTipText("");
        btn_localidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_localidadActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Teléfono");

        txt_telefono.setBackground(new java.awt.Color(255, 255, 255));

        btn_cargarcv.setBackground(new java.awt.Color(204, 204, 204));
        btn_cargarcv.setForeground(new java.awt.Color(0, 0, 0));
        btn_cargarcv.setText("Cargar C.V del candidato");
        btn_cargarcv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarcvActionPerformed(evt);
            }
        });

        Date_calendario.setBackground(new java.awt.Color(255, 255, 255));
        Date_calendario.setForeground(new java.awt.Color(255, 255, 255));

        btn_registrar.setBackground(new java.awt.Color(153, 153, 153));
        btn_registrar.setForeground(new java.awt.Color(0, 0, 0));
        btn_registrar.setText("Registrar");
        btn_registrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_cp, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_localidad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(235, 235, 235))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(43, 43, 43)
                                    .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_dni, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                        .addComponent(Date_calendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btn_cargarcv)
                                .addGap(79, 79, 79)
                                .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btn_localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cargarcv)
                    .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos complementarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));

        txt_observaciones.setBackground(new java.awt.Color(255, 255, 255));
        txt_observaciones.setColumns(20);
        txt_observaciones.setRows(5);
        jScrollPane1.setViewportView(txt_observaciones);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Estudios finalizados");

        btn_estudiosfinalizados.setBackground(new java.awt.Color(204, 204, 204));
        btn_estudiosfinalizados.setForeground(new java.awt.Color(0, 0, 0));
        btn_estudiosfinalizados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "ESO", "Bachillerato", "Grado medio", "Grado Superior", "Universitarios" }));
        btn_estudiosfinalizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estudiosfinalizadosActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nivel de informática");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Otras observaciones");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Tratamiento de textos");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Hoja de cálculo");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Internet");

        btn_usuariotextos.setBackground(new java.awt.Color(204, 204, 204));
        btn_usuariotextos.setForeground(new java.awt.Color(0, 0, 0));
        btn_usuariotextos.setText("Usuario");
        btn_usuariotextos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuariotextosActionPerformed(evt);
            }
        });

        btn_usuariocalculos.setBackground(new java.awt.Color(204, 204, 204));
        btn_usuariocalculos.setForeground(new java.awt.Color(0, 0, 0));
        btn_usuariocalculos.setText("Usuario");
        btn_usuariocalculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuariocalculosActionPerformed(evt);
            }
        });

        btn_avanzadotextos.setBackground(new java.awt.Color(204, 204, 204));
        btn_avanzadotextos.setForeground(new java.awt.Color(0, 0, 0));
        btn_avanzadotextos.setText("Avanzado");
        btn_avanzadotextos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_avanzadotextosActionPerformed(evt);
            }
        });

        btn_mediocalculo.setBackground(new java.awt.Color(204, 204, 204));
        btn_mediocalculo.setForeground(new java.awt.Color(0, 0, 0));
        btn_mediocalculo.setText("Medio");
        btn_mediocalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mediocalculoActionPerformed(evt);
            }
        });

        btn_avanzadocalculo.setBackground(new java.awt.Color(204, 204, 204));
        btn_avanzadocalculo.setForeground(new java.awt.Color(0, 0, 0));
        btn_avanzadocalculo.setText("Avanzado");
        btn_avanzadocalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_avanzadocalculoActionPerformed(evt);
            }
        });

        btn_usuariointernet.setBackground(new java.awt.Color(204, 204, 204));
        btn_usuariointernet.setForeground(new java.awt.Color(0, 0, 0));
        btn_usuariointernet.setText("Usuario");
        btn_usuariointernet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuariointernetActionPerformed(evt);
            }
        });

        btn_mediotextos.setBackground(new java.awt.Color(204, 204, 204));
        btn_mediotextos.setForeground(new java.awt.Color(0, 0, 0));
        btn_mediotextos.setText("Medio");
        btn_mediotextos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mediotextosActionPerformed(evt);
            }
        });

        btn_mediointernet.setBackground(new java.awt.Color(204, 204, 204));
        btn_mediointernet.setForeground(new java.awt.Color(0, 0, 0));
        btn_mediointernet.setText("Medio");
        btn_mediointernet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mediointernetActionPerformed(evt);
            }
        });

        btn_avanzadointernet.setBackground(new java.awt.Color(204, 204, 204));
        btn_avanzadointernet.setForeground(new java.awt.Color(0, 0, 0));
        btn_avanzadointernet.setText("Avanzado");
        btn_avanzadointernet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_avanzadointernetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator2)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_estudiosfinalizados, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_usuariotextos)
                                    .addComponent(btn_usuariocalculos)
                                    .addComponent(btn_usuariointernet))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(btn_mediointernet)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_avanzadointernet))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(btn_mediocalculo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_avanzadocalculo))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(btn_mediotextos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_avanzadotextos))))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_estudiosfinalizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(btn_usuariotextos)
                    .addComponent(btn_mediotextos)
                    .addComponent(btn_avanzadotextos))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(btn_usuariocalculos)
                    .addComponent(btn_mediocalculo)
                    .addComponent(btn_avanzadocalculo))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(btn_usuariointernet)
                    .addComponent(btn_mediointernet)
                    .addComponent(btn_avanzadointernet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1116, 708));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void btn_estudiosfinalizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estudiosfinalizadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_estudiosfinalizadosActionPerformed

    private void btn_localidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_localidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_localidadActionPerformed

    JFileChooser selArchivos = new JFileChooser();
   
    String comprobacioncp= "[0-9]{5}";
    String comprobaciondni = "[0-9]{8}[A-Za-z]{1}";
    String comprobaciontelefono = "[6,7,8,9]{1}[0-9]{8}";

    
    public void registraradministracicon() {
        
        if(txt_nombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Inserte un nombre");
        }else if(txt_apellidos.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Inserte un apellido");
        }else if(txt_dni.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Inserte un dni");
        }else if(!Pattern.matches(comprobaciondni, txt_dni.getText())){
            JOptionPane.showMessageDialog(null, "Formato dni incorrecto");
        }else if(Date_calendario.getDate()==null){
            JOptionPane.showMessageDialog(null, "Inserte una fecha de nacimiento");
        }else if(txt_direccion.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Inserte una direccion");
        }else if(txt_cp.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Inserte un codigo postal");
        }else if(!Pattern.matches(comprobacioncp, txt_cp.getText())){
            JOptionPane.showMessageDialog(null, "Formato de codigo postal no valido");
        }else if(btn_localidad.equals("Seleccione")){
            JOptionPane.showMessageDialog(null, "Seleccione una localidad");
        }else if(txt_telefono.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Inserte un telefono");
        }else if(!Pattern.matches(comprobaciontelefono, txt_telefono.getText())){
            JOptionPane.showMessageDialog(null, "Formato de telefono no valido");
        }else if(btn_estudiosfinalizados.equals("Seleccione")){
            JOptionPane.showMessageDialog(null, "Seleccione los estudios finalizados");
        }else if(txt_observaciones.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Inserte observaciones");
        }else if(selArchivos.getSelectedFile()==null){
            JOptionPane.showMessageDialog(null, "Seleccione cv");
        }else{
            
            File f = new File(selArchivos.getSelectedFile().getAbsolutePath());
            movfichero(f);
            f.renameTo(new File(System.currentTimeMillis()+obtextension(f)));
            Date date = new Date();
            
            String nombre = txt_nombre.getText();
            String apellido = txt_apellidos.getText();
            String dni = txt_dni.getText();
            String fnacimiento = String.valueOf(Date_calendario.getDate());
            String direccion = txt_direccion.getText();
            int cp = Integer.parseInt(txt_cp.getText());
            String localidad = btn_localidad.getSelectedItem().toString();
            int telefono = Integer.parseInt(txt_telefono.getText());
            String rutacv = f.getName();
            String nivelestudios = btn_estudiosfinalizados.getSelectedItem().toString();
            String observaciones = txt_observaciones.getText();
            String fechaAlta = ffecha(date);
            
            String tratamienttextos="";
            String tratamientohojas="";
            String tratamientointernet="";
            
            if(btn_usuariotextos.isSelected()){
                tratamienttextos="Usuario";
            }else if(btn_mediotextos.isSelected()){
                tratamienttextos="Medio";
            }else if(btn_avanzadotextos.isSelected()){
                tratamienttextos="Avanzado";
            }
            
            if(btn_usuariocalculos.isSelected()){
                tratamientohojas = "Usuario";
            }else if(btn_mediocalculo.isSelected()){
                tratamientohojas = "Medio";
            }else if(btn_avanzadocalculo.isSelected()){
                tratamientohojas = "Avanzado";
            }
            
            if(btn_usuariointernet.isSelected()){
                tratamientointernet = "Usuario";
            }else if(btn_mediointernet.isSelected()){
                tratamientointernet = "Medio";
            }else if(btn_avanzadointernet.isSelected()){
                tratamientointernet = "Avanzado";
            }
            String usuarioRegistrador = Login.registrador;
            
            Administracion ob = new Administracion(tratamienttextos, tratamientohojas, tratamientointernet, nombre, apellido, dni, fnacimiento,
            direccion, cp, localidad, telefono, rutacv, nivelestudios, observaciones, fechaAlta, usuarioRegistrador);
            
            conexion.conectar();
            
            if(conexion.registrarAdministracion(ob)){
                conexion.cerrarconexion();
                Fichero fic = new Fichero(fca);
                fic.escribir(ob.toString());
                JOptionPane.showMessageDialog(null, "Registrocorrecto");
                limpiarcampos();
            }else{
                JOptionPane.showMessageDialog(null, "Registro incorrecto");
            }
            
        }
    }
   
    public String ffecha(Date fecha){
        String fechas=null;
        SimpleDateFormat ob = new SimpleDateFormat("dd-mm-yyyy");
        fechas = ob.format(fecha);
        return fechas;
    }
    
    public void movfichero(File fichero){
        Path or = Paths.get(fichero.getAbsolutePath());
        Path des = Paths.get("CV/"+ System.currentTimeMillis()+obtextension(fichero));
        System.out.println(des.toAbsolutePath());
        try {
            Files.copy(or, des, REPLACE_EXISTING);
        } catch (IOException ex) {
            Logger.getLogger(CandidatosAdministracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public String obtextension(File fichero){
        String ex = "";
        String nomfichero = fichero.getName();
        
        int i = nomfichero.lastIndexOf('.');
        if(i>0){
            ex=nomfichero.substring(i);
        }
        return ex;
    }
    
    public void limpiarcampos(){
        txt_nombre.setText("");
        txt_cp.setText("");
        txt_apellidos.setText("");
        txt_direccion.setText("");
        txt_dni.setText("");
        txt_observaciones.setText("");
        txt_telefono.setText("");
    }


    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        registraradministracicon();
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void btn_usuariotextosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuariotextosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_usuariotextosActionPerformed

    private void btn_usuariocalculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuariocalculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_usuariocalculosActionPerformed

    private void btn_avanzadotextosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_avanzadotextosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_avanzadotextosActionPerformed

    private void btn_mediocalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mediocalculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_mediocalculoActionPerformed

    private void btn_avanzadocalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_avanzadocalculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_avanzadocalculoActionPerformed

    private void btn_usuariointernetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuariointernetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_usuariointernetActionPerformed

    private void btn_mediotextosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mediotextosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_mediotextosActionPerformed

    private void btn_mediointernetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mediointernetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_mediointernetActionPerformed

    private void btn_avanzadointernetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_avanzadointernetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_avanzadointernetActionPerformed

    private void btn_cargarcvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarcvActionPerformed
        selArchivos.showOpenDialog(this);
    }//GEN-LAST:event_btn_cargarcvActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CandidatosAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CandidatosAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CandidatosAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CandidatosAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CandidatosAdministracion dialog = new CandidatosAdministracion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_calendario;
    private javax.swing.JRadioButton btn_avanzadocalculo;
    private javax.swing.JRadioButton btn_avanzadointernet;
    private javax.swing.JRadioButton btn_avanzadotextos;
    private javax.swing.JButton btn_cargarcv;
    private javax.swing.JComboBox<String> btn_estudiosfinalizados;
    private javax.swing.JComboBox<String> btn_localidad;
    private javax.swing.JRadioButton btn_mediocalculo;
    private javax.swing.JRadioButton btn_mediointernet;
    private javax.swing.JRadioButton btn_mediotextos;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JRadioButton btn_usuariocalculos;
    private javax.swing.JRadioButton btn_usuariointernet;
    private javax.swing.JRadioButton btn_usuariotextos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_cp;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_dni;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextArea txt_observaciones;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
